// https://docs.gradle.org/8.10/javadoc/org/gradle/api/Project.html

plugins {
	id 'java'
}

def pluginProjectVersion = '1.0.0'
def pluginProjectName    = "${rootProject.name}"
def pluginPackage        = 'com.lita'
def pluginGroup          = pluginPackage
def pluginMainClass      = "${pluginPackage}.${pluginProjectName}Plugin"
def pluginTestClass      = "${pluginMainClass}Test"
def pluginJarName        = "${pluginProjectName}-${pluginProjectVersion}-all.jar"
def pluginJarGroup       = BasePlugin.BUILD_GROUP
def runeLiteVersion      = 'latest.release'

project.version = pluginProjectVersion

repositories {
	mavenLocal()
	maven {
		url = 'https://repo.runelite.net'
		content {
			includeGroupByRegex("net\\.runelite.*")
		}
	}
	mavenCentral()
}

dependencies {
	compileOnly group: 'net.runelite', name:'client', version: runeLiteVersion

	compileOnly 'org.projectlombok:lombok:1.18.30'
	annotationProcessor 'org.projectlombok:lombok:1.18.30'

	testImplementation 'junit:junit:4.12'
	testImplementation group: 'net.runelite', name:'client', version: runeLiteVersion
	testImplementation group: 'net.runelite', name:'jshell', version: runeLiteVersion

	implementation group: 'net.runelite', name: 'client', version: runeLiteVersion
	implementation group: 'net.runelite', name: 'jshell', version: runeLiteVersion
}

group = pluginGroup

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
//	options.release.set(11)
}

// https://docs.gradle.org/8.10/javadoc/org/gradle/api/tasks/TaskContainer.html#register(java.lang.String,java.lang.Class)
// https://docs.gradle.org/8.10/javadoc/org/gradle/api/tasks/JavaExec.html
tasks.register('runTest', JavaExec) {
	classpath = sourceSets.test.runtimeClasspath
	mainClass = pluginTestClass
	jvmArgs "-ea"
	args "--developer-mode"
}

tasks.register('runMain', JavaExec) {
	classpath = sourceSets.main.runtimeClasspath
	mainClass = pluginMainClass
	jvmArgs "-ea"
	args "--developer-mode"
}

// https://docs.gradle.org/8.10/javadoc/org/gradle/api/tasks/bundling/Jar.html
tasks.register('shadowJar', Jar) {
	dependsOn configurations.testRuntimeClasspath
	manifest {
		attributes('Main-Class': pluginMainClass, 'Multi-Release': true)
	}

	duplicatesStrategy = DuplicatesStrategy.EXCLUDE

	// https://docs.gradle.org/8.10/javadoc/org/gradle/api/tasks/AbstractCopyTask.html#from(java.lang.Object...)
	from sourceSets.main.output
	from sourceSets.test.output
	from {
		configurations.testRuntimeClasspath.collect { file ->
			file.isDirectory() ? file : zipTree(file)
		}
	}

	exclude 'META-INF/INDEX.LIST'
	exclude 'META-INF/*.SF'
	exclude 'META-INF/*.DSA'
	exclude 'META-INF/*.RSA'
	exclude '**/module-info.class'

	group = pluginJarGroup

	// https://docs.gradle.org/8.10/javadoc/org/gradle/api/tasks/bundling/AbstractArchiveTask.html#getArchiveClassifier()
	archiveClassifier.set('shadow')

	archiveFileName.set(pluginJarName)
}