displayName=Wildy Agility Loot Tracker
author=RSN:Karol920/GitHub:Mr920/Name:Charles Lentz
description=Keeps track of loot received at wildy agility course, on a per-session basis
tags=wilderness,wildy,agility,loot,tracker
version=2.0.0
plugins=com.lita.WildyAgilityLootTrackerPlugin
build=standard
# It seems stupid I can't use these values inside the annotation properties on class definition... I should come up with
# a means of unifying the values in the .properties file with the class annoation properties in some kinda of
# dynamic fashion at some point....