displayName=Wildy_Agility_Loot_Tracker
author=Charles_Lentz
description=Keeps track of loot received at wildy agility course, on a per-session basis
tags=
version=
plugins=com.lita.WildyAgilityLootTrackerPlugin
build=standard
